# Generated by Django 2.2.8 on 2019-12-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
