# Generated by Django 2.2.8 on 2019-12-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
