# Generated by Django 2.2.8 on 2019-12-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191207_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='summary',
            field=models.TextField(),
        ),
    ]
